name: Hello World

on:
  push:
    branches: [ "main" ]

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Output Hello World
      run: echo "Hello World - from Github Actions"
